# Generated by Django 4.2.7 on 2023-11-15 11:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100, verbose_name='место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='время')),
                ('action', models.TextField(verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('period', models.CharField(choices=[('DAILY', 'каждый день'), ('WEEKLY', 'раз в неделю')], default='DAILY', max_length=15, verbose_name='периодичность')),
                ('award', models.TextField(blank=True, null=True, verbose_name='вознаграждение')),
                ('time_to_complete', models.TimeField(default=datetime.time(0, 2), verbose_name='время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='создатель привычки')),
                ('pleasant_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='приятная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
